apiVersion: v1
kind: ConfigMap
metadata:
  name: green-config
  namespace: default
data:
  DB_HOST: "34.27.23.176"
  DB_PORT: "3306"
  DB_NAME: "green_special"
  REACT_APP_API_URL: "https://greenapi.novepharm.store"
